import { z } from 'zod';

export const taskSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  description: z.string().optional().or(z.literal('')),
  project: z.string().optional().or(z.literal('')),
  client: z.string().optional().or(z.literal('')),
  department: z.string().optional().or(z.literal('')),
  priority: z.enum(['low', 'medium', 'high', 'urgent']),
  taskType: z.enum([
    'development',
    'bugfix',
    'meeting',
    'testing',
    'research',
    'design',
    'support',
    'deployment',
    'documentation',
    'training',
    'other',
  ]),
  startTime: z.string().optional().or(z.literal('')),
  endTime: z.string().optional().or(z.literal('')),
  taskDate: z.string().min(1, 'Task date is required'),
  expectedCompletion: z.string().optional().or(z.literal('')),
  actualCompletion: z.string().optional().or(z.literal('')),
  status: z.enum(['pending', 'in-progress', 'completed', 'hold', 'cancelled']),
  remarks: z.string().optional().or(z.literal('')),
  githubLink: z.string().optional().or(z.literal('')),
  taskUrl: z.string().optional().or(z.literal('')),
  notes: z.string().optional().or(z.literal('')),
  assignedTo: z.string().optional().or(z.literal('')),
});
